/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./src/components/_common/Card/Card.vue')['default']
    CardList: typeof import('./src/components/CardList/CardList.vue')['default']
    ClSearchMagnifyingGlass: typeof import('@kalimahapps/vue-icons/cl')['ClSearchMagnifyingGlass']
    DropdownSearch: typeof import('./src/components/_common/DropdownSearch/DropdownSearch.vue')['default']
    FlGlobeSearch: typeof import('@kalimahapps/vue-icons/fl')['FlGlobeSearch']
    Header: typeof import('./src/components/Header/Header.vue')['default']
    LoadingSpinner: typeof import('./src/components/_common/LoadingSpinner/LoadingSpinner.vue')['default']
    MdRoundArrowBackIos: typeof import('@kalimahapps/vue-icons/md')['MdRoundArrowBackIos']
    MdRoundClear: typeof import('@kalimahapps/vue-icons/md')['MdRoundClear']
    Search: typeof import('./src/components/_common/Search/Search.vue')['default']
  }
}
